### ISSUE TITLE
LXCFS bug possibly causing SIGFPE in fsck

### ISSUE THREAD

**Issue by jaskij** [tytso/e2fsprogs#114]
I am not entirely sure if this is the right place for filing bugs, but here goes.

Due to [a bug in `lxcfs` ](https://github.com/lxc/lxcfs/issues/469) `sysconf(_SC_NPROCESSORS_CONF)` can return 0.

This seems to cause a division by zero [in `rw_bitmaps.c`](https://github.com/tytso/e2fsprogs/blob/96185e9bef1dca5a3b7d93f244d65107aad5f37f/lib/ext2fs/rw_bitmaps.c#L562). Which in turn breaks builds when using OpenEmbedded under LXC.

A quick and dirty fix would be to simply change `<` to `<=` [here](https://github.com/tytso/e2fsprogs/blob/96185e9bef1dca5a3b7d93f244d65107aad5f37f/lib/ext2fs/rw_bitmaps.c#L557).

A better way would probably involve using [`sched_getaffinity()`](https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html) together with the [`CPU_COUNT`](https://man7.org/linux/man-pages/man3/CPU_SET.3.html) macro as an alternative source.

https://github.com/tytso/e2fsprogs/blob/96185e9bef1dca5a3b7d93f244d65107aad5f37f/lib/ext2fs/rw_bitmaps.c#L546-L568

**Comment by tytso** [comment]
Thanks for reporting this; we will use the quick and dirty fix that you suggested.
