### ISSUE TITLE
RFE: Support SOURCE_DATE_EPOCH and timestamp clamping

### ISSUE THREAD

**Issue by nl6720** [tytso/e2fsprogs#131]
e1f7100643a46456be107b33098f6034b0835e6d added support for a e2fsprogs-specific variable `E2FSPROGS_FAKE_TIME`. But as the commit message says, you still need to manually set a reproducible hash seed.

It would be useful if e2fsprogs could support [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/). I.e. if `SOURCE_DATE_EPOCH` is set, use it as the mkfs timestamp and generate a reproducible hash seed from it.

Additionally, `mkfs.ext4 -d` reproducibility requires [timestamp clamping](https://reproducible-builds.org/specs/source-date-epoch/#idm55). The various timestamps of files in the file system should not be newer than `SOURCE_DATE_EPOCH`.

**Comment by tytso** [comment]
The hash seed is not actually time based (it's a random value), so it seems at odds with the definition of SOURCE_DATE_EPOCH to say that we should change how the hash seed is generated.   I understand why this would be considered "convenient", but it still seems strange.

**Comment by katexochen** [comment]
> so it seems at odds with the definition of SOURCE_DATE_EPOCH to say that we should change how the hash seed is generated

I agree, this would be somewhat unexpected.

But I would really love to see `SOURCE_DATE_EPOCH` respected, and support for timestamp clamping seems to be a great idea, too.

**Comment by tytso** [comment]
SOURCE_DATE_EPOCH has been implementing with timestamp clamping in v1.47.1-rc1+
