### ISSUE TITLE
Extraneous tab inside output of tune2fs

### ISSUE THREAD

**Issue by hochl** [tytso/e2fsprogs#165]
I recently found two stray tabs inside the output of _tune2fs -l_. Since these are the only two tab characters in the output, I guess this is a mistake that was introduced in commit `41a5afa87 (Theodore Ts'o   2008-04-20 16:10:07 -0400 363)`. I created a patch to replace them with spaces like in all other fields and attached it to this issue.
[ls_c.patch.gz](https://github.com/tytso/e2fsprogs/files/13268347/ls_c.patch.gz)

**Comment by richardfearn** [comment]
@hochl I came across this today as well. I converted your patch into a PR: #169
