### ISSUE TITLE
Allow setting root dir permissions directly in mke2fs

### ISSUE THREAD

**Issue by haarp** [tytso/e2fsprogs#168]
Hello,

currently there is a way of setting the owner of the root directory in mke2fs (`-E root_owner`), but not the permissions. To do this, the fs needs to be mounted first, followed by chmod, followed by unmount. This is not always convenient, e.g. when scripts are used to create a fs. My particular use case involves running ext4 on [zram](https://www.kernel.org/doc/html/next/admin-guide/blockdev/zram.html) devices.

This has been asked a couple of times on Stack Exchange too: [1](https://unix.stackexchange.com/q/422656/138699), [2](https://unix.stackexchange.com/q/650901/138699)

Would it be possible to add a `root_perms` extended option aswell?

Thanks a lot!

**Comment by chestnykh** [comment]
Hi! I've created PR that adds `root_perms` option. Can someone review it?

**Comment by haarp** [comment]
Thanks both of you!
