### ISSUE TITLE
Is mke2fs GPLv3 compatible?

### ISSUE THREAD

**Issue by AnuthaDev** [tytso/e2fsprogs#177]
Is it GPL-2.0-only or can it be used in GPLv3 source?

**Comment by tytso** [comment]
Like the Linux kernel, e2fsprogs is GPL-2 only.   Of course, GPL-3 code can run a GPL-2 program using fork-exec, which is how mke2fs is generally run.  But if you were going to try to incorporate mke2fs source code or libext2fs library in GPLv3 source code, I would invite you to investigate relicensing your source code to GPL-2.

For my (and Linus's) rationale for our license choice, please see the video "[Linus Torvalds says GPL v3 violates everything that GPLv2 stood for](https://www.youtube.com/watch?v=PaKIZ7gJlRU)."

**Comment by AnuthaDev** [comment]
Ok 🥲
