### ISSUE TITLE
Build failure with GCC 15 (C23)

### ISSUE THREAD

**Issue by kostadinsh** [tytso/e2fsprogs#202]
Upcoming GCC 15 uses -std=gnu23 by default which makes e2fsprogs fail to build.

The issue can be reproduced on older GCC and Clang versions by adding -std=gnu23 (for GCC) and -std=c23 (for Clang) to CFLAGS.

Downstream bug report in Gentoo: https://bugs.gentoo.org/943687

```
tdb.c:113:13: error: two or more data types in declaration specifiers
  113 | typedef int bool;
      |             ^~~~
```

**Comment by tytso** [comment]
This should be fixed by the above mentioned commit.

**Comment by kostadinsh** [comment]
> This should be fixed by the above mentioned commit.

It is indeed. Thanks!
