### ISSUE TITLE
Six tests fail often in Nixpkgs package

### ISSUE THREAD

**Issue by FRidh** [tytso/e2fsprogs#21]
The following tests often fail with 1.45.2 and 1.45.3. The issue did not occur before.
```
Tests failed: m_image_mmp m_mmp m_mmp_bad_csum m_mmp_bad_magic t_mmp_1on t_mmp_2off 
```
Related issue on our tracker: https://github.com/NixOS/nixpkgs/issues/65471.

Any idea why it is failing often but not always?

**Comment by tytso** [comment]
Answered at https://github.com/NixOS/nixpkgs/issues/65471#issuecomment-601976438

**Comment by FRidh** [comment]
Thank you!
