### ISSUE TITLE
FSCK Memory leak with mdadm

### ISSUE THREAD

**Issue by SebZero** [tytso/e2fsprogs#22]
Hi all, i have an issue while running fsck on a partition created on a soft raid 5
The process have a big leak during the last sequence (step 5) and is using the entire memory on the system (1GB) and is killed by the kernel

It's occurs with version 1.43 and 1.45
The OS is a custom OS built with buildroot but we dont have the issue with the hardware raid on the same platform.

Regards,
Seb

**Comment by tytso** [comment]
Is this a userspace leak?   I don't see how software vs. harwdware raid would make a difference if it the leak is of user memory.

Can you run e2fsck under valgrind, perhaps with a smaller file systems so it doesn't crash, so we can see what is getting leaked?   For example:

% valgrind --leak-check=yes e2fsck -fy /tmp/foo.img
==7863== Memcheck, a memory error detector
==7863== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==7863== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==7863== Command: e2fsck -fy /tmp/foo.img
==7863== 
e2fsck 1.45.3 (14-Jul-2019)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/tmp/foo.img: 11/128 files (0.0% non-contiguous), 42/1024 blocks
==7863== 
==7863== HEAP SUMMARY:
==7863==     in use at exit: 0 bytes in 0 blocks
==7863==   total heap usage: 510 allocs, 510 frees, 282,579 bytes allocated
==7863== 
==7863== All heap blocks were freed -- no leaks are possible
==7863== 
==7863== For lists of detected and suppressed errors, rerun with: -s
==7863== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by tytso** [comment]
How do you know that it is even a memory leak, versus, not just having enough memory on your system.  How big is the file system, and how much memory do you have on your system.  Can you disconnect your file system from your embedded system, put it on a properly system with sufficient memory, and then run "e2fsck -fvytt /dev/XXX" and include the output in your message?  It will look like this:
<tytso.root@lambda> {/usr/projects/linux/ext4}, level 2   (guilt/d)
1002# e2fsck -fyvtt /dev/lambda/old-files 
e2fsck 1.45.3 (14-Jul-2019)
Pass 1: Checking inodes, blocks, and sizes
Pass 1: Memory used: 772k/2068k (670k/102k), time:  0.41/ 0.25/ 0.09
Pass 1: I/O read: 78MB, write: 0MB, rate: 189.06MB/s
Pass 2: Checking directory structure
Pass 2: Memory used: 1300k/2480k (598k/703k), time:  0.28/ 0.15/ 0.13
Pass 2: I/O read: 82MB, write: 0MB, rate: 291.58MB/s
Pass 3: Checking directory connectivity
Peak memory: Memory used: 1300k/2480k (598k/703k), time:  0.72/ 0.41/ 0.22
Pass 3A: Memory used: 1300k/2480k (659k/642k), time:  0.00/ 0.00/ 0.00
Pass 3A: I/O read: 0MB, write: 0MB, rate: 0.00MB/s
Pass 3: Memory used: 1300k/2296k (597k/704k), time:  0.00/ 0.00/ 0.00
Pass 3: I/O read: 1MB, write: 0MB, rate: 824.40MB/s
Pass 4: Checking reference counts
Pass 4: Memory used: 1300k/0k (399k/902k), time:  0.06/ 0.05/ 0.01
Pass 4: I/O read: 0MB, write: 0MB, rate: 0.00MB/s
Pass 5: Checking group summary information
Pass 5: Memory used: 1300k/0k (335k/966k), time:  0.02/ 0.02/ 0.00
Pass 5: I/O read: 3MB, write: 0MB, rate: 180.74MB/s

      283419 inodes used (4.32%, out of 6553600)
        2692 non-contiguous files (0.9%)
         173 non-contiguous directories (0.1%)
             # of inodes with ind/dind/tind blocks: 0/0/0
             Extent depth histogram: 280201/61
    20262147 blocks used (77.29%, out of 26214400)
           0 bad blocks
           2 large files

      263719 regular files
       15620 directories
          23 character device files
           2 block device files
           6 fifos
         764 links
        4022 symbolic links (3100 fast symbolic links)
          18 sockets
------------
      284174 files
Memory used: 1300k/0k (335k/966k), time:  0.80/ 0.48/ 0.23
I/O read: 164MB, write: 1MB, rate: 205.45MB/s

Also including the output of dumpe2fs -h /dev/XXX would also be helpful.

**Comment by tytso** [comment]
You've not given me any proof of a leak, and your definition of leak seems very strange --- apparently it means, you think e2fsck should use less memory when you try to run e2fsck on a file system which is too large.    If you can find me absolute proof of a memory leak, via valgrind:

# valgrind --leak-check=yes e2fsck -fy /dev/lambda/old-files
==21112== Memcheck, a memory error detector
==21112== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==21112== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==21112== Command: e2fsck -fy /dev/lambda/old-files
==21112== 
e2fsck 1.45.3 (14-Jul-2019)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/lambda/old-files: 283419/6553600 files (1.0% non-contiguous), 20262147/26214400 blocks
==21112== 
==21112== HEAP SUMMARY:
==21112==     in use at exit: 0 bytes in 0 blocks
==21112==   total heap usage: 1,313,946 allocs, 1,313,946 frees, 108,487,830 bytes allocated
==21112== 
==21112== All heap blocks were freed -- no leaks are possible
==21112== 
==21112== For lists of detected and suppressed errors, rerun with: -s
==21112== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

I invite you to open a new bug.  Until then, I'm closing this as not reproducible.
