### ISSUE TITLE
Should not install blkid.h

### ISSUE THREAD

**Issue by lal12** [tytso/e2fsprogs#27]
I don't think it should install /usr/include/blkid/blkid.h it is a very old version and even a privately used library.

This probably applies to all other util-linux libs too (like uuid).

**Comment by tytso** [comment]
E2fsprogs only installs blkid.h if the blkid library is built.   And if the util-linux provided blkid library is detected by the configure script, blkid won't be built unless there is a --enable-libblkid option specified to the configure script to explicitly request that it be built. 

The same is true for libuuid.

There are platforms which don't have util-linux installed or built --- in particular, FreeBSD, Illumos (and other Open Solaris derivatives), and android, where libblkid and libuuid are still built and used.  But on modern linux systems, by default libblkid and libuuid are not built and the header file is not installed.

```
<tytso@lambda> {/build/e2fsprogs-maint}  
1247% make install DESTDIR=/tmp/d >& /dev/null
<tytso@lambda> {/build/e2fsprogs-maint}  
1248% ls -lR /tmp/d/usr/include
/tmp/d/usr/include:
total 4
4 -rw-r--r-- 2 tytso tytso 2118 Dec 11 11:14 com_err.h
0 drwxr-xr-x 2 tytso tytso   60 Dec 11 11:14 e2p/
0 drwxr-xr-x 2 tytso tytso   60 Dec 11 11:14 et/
0 drwxr-xr-x 2 tytso tytso  260 Dec 11 11:14 ext2fs/
0 drwxr-xr-x 2 tytso tytso   80 Dec 11 11:14 ss/

/tmp/d/usr/include/e2p:
total 4
4 -rw-r--r-- 1 tytso tytso 3139 Dec 11 11:14 e2p.h

/tmp/d/usr/include/et:
total 4
4 -rw-r--r-- 2 tytso tytso 2118 Dec 11 11:14 com_err.h

/tmp/d/usr/include/ext2fs:
total 200
24 -rw-r--r-- 1 tytso tytso 22148 Dec 11 11:14 bitops.h
12 -rw-r--r-- 1 tytso tytso 11784 Dec 11 11:14 ext2_err.h
 4 -rw-r--r-- 1 tytso tytso  2644 Dec 11 11:14 ext2_ext_attr.h
44 -rw-r--r-- 1 tytso tytso 41959 Dec 11 11:14 ext2_fs.h
72 -rw-r--r-- 1 tytso tytso 71441 Dec 11 11:14 ext2fs.h
 8 -rw-r--r-- 1 tytso tytso  5391 Dec 11 11:14 ext2_io.h
 8 -rw-r--r-- 1 tytso tytso  4212 Dec 11 11:14 ext2_types.h
 8 -rw-r--r-- 1 tytso tytso  4558 Dec 11 11:14 ext3_extents.h
 4 -rw-r--r-- 1 tytso tytso  1179 Dec 11 11:14 hashmap.h
 4 -rw-r--r-- 1 tytso tytso  2588 Dec 11 11:14 qcow2.h
12 -rw-r--r-- 1 tytso tytso  8871 Dec 11 11:14 tdb.h

/tmp/d/usr/include/ss:
total 8
4 -rw-r--r-- 1 tytso tytso 1193 Dec 11 11:14 ss_err.h
4 -rw-r--r-- 1 tytso tytso 3166 Dec 11 11:14 ss.h
<tytso@lambda> {/build/e2fsprogs-maint}  
1249% find /tmp/d -name blkid\*
<tytso@lambda> {/build/e2fsprogs-maint}  
1250% 
```

**Comment by lal12** [comment]
Hmm I am pretty sure that it is correctly linked to the local util-linux. So I guess the detection is not working correctly in my build process. I will look into this.
