### ISSUE TITLE
How to define __linux__ automatically?

### ISSUE THREAD

**Issue by pahome** [tytso/e2fsprogs#35]
I tried to enable debug mode in resize/resize2fs.c and I saw one definition:
```
#ifdef __linux__                        /* Kludge for debugging */
#define RESIZE2FS_DEBUG
#endif
```
How to define the `__linux__` automatically? what options when setup configure?
My OS is Ubuntu 16.04.

**Comment by tytso** [comment]
__linux__ is defined by default when compiling on Linux.  Ubuntu runs Linux, so it's defined automatically without your needing to do anything.

This is something that was used back when the resize2fs code was also by Partition Magic running on Windows, and so the main goal was to suppress the printf statements when compiling for Windows ME (it was a long time ago). 

See the man page for resize2fs.   You can enable various debugging flags by using the -d flag.   It's really only useful for developers of e2fsprogs.   For others, it will probably be booring or way too much information to the point of being confusing.   It's not meant for "civilians"  :-)

% mke2fs -t ext4 -Fq /tmp/foo.img 100k
Filesystem too small for a journal

% resize2fs -d 63 /tmp/foo.img 1G
resize2fs 1.45.6 (20-Mar-2020)
fs has 11 inodes, 1 groups required.
fs requires 15 data blocks.
With 1 group(s), we have 8186 blocks available.
Last group's overhead is 6
Need 15 data blocks in last group
Final size of last group is 57
Estimated blocks needed: 57
Extents safety margin: 0
Resizing the filesystem on /tmp/foo.img to 1048576 (1k) blocks.
read_bitmaps: Memory used: 132k/0k (30k/103k), time:  0.00/ 0.00/ 0.00
read_bitmaps: I/O read: 1MB, write: 0MB, rate: 16666.67MB/s
fix_uninit_block_bitmaps 1: Memory used: 132k/0k (30k/103k), time:  0.00/ 0.00/ 0.00
resize_group_descriptors: Memory used: 132k/0k (32k/101k), time:  0.00/ 0.00/ 0.00
move_bg_metadata: Memory used: 132k/0k (32k/101k), time:  0.00/ 0.00/ 0.00
zero_high_bits_in_metadata: Memory used: 132k/0k (32k/101k), time:  0.00/ 0.00/ 0.00
adjust_superblock: Memory used: 132k/0k (42k/91k), time:  0.00/ 0.00/ 0.00
fix_uninit_block_bitmaps 2: Memory used: 132k/0k (42k/91k), time:  0.00/ 0.00/ 0.00
blocks_to_move: Memory used: 132k/0k (43k/90k), time:  0.00/ 0.00/ 0.00
Number of free blocks: 79/1047348, Needed: 7
Moving 6 blocks 4->82
block_mover: Memory used: 132k/0k (47k/86k), time:  0.00/ 0.00/ 0.00
block_mover: I/O read: 1MB, write: 1MB, rate: 5000.00MB/s
ino=2, blockcnt=0, 4->82
ino=11, blockcnt=0, 5->83
ino=11, blockcnt=1, 6->84
ino=11, blockcnt=2, 7->85
ino=11, blockcnt=3, 8->86
ino=11, blockcnt=4, 9->87
inode_scan_and_fix: Memory used: 132k/0k (48k/85k), time:  0.00/ 0.00/ 0.00
inode_scan_and_fix: I/O read: 1MB, write: 1MB, rate: 4219.41MB/s
inode_ref_fix: Memory used: 132k/0k (48k/85k), time:  0.00/ 0.00/ 0.00
move_itables: Memory used: 132k/0k (48k/85k), time:  0.00/ 0.00/ 0.00
calculate_summary_stats: Memory used: 132k/0k (48k/85k), time:  0.05/ 0.05/ 0.00
fix_resize_inode: Memory used: 132k/0k (50k/83k), time:  0.00/ 0.00/ 0.00
fix_sb_journal_backup: Memory used: 132k/0k (50k/83k), time:  0.00/ 0.00/ 0.00
overall resize2fs: Memory used: 132k/0k (50k/83k), time:  0.05/ 0.05/ 0.00
overall resize2fs: I/O read: 1MB, write: 1MB, rate: 20.22MB/s
The filesystem on /tmp/foo.img is now 1048576 (1k) blocks long.
