### ISSUE TITLE
Error while trying to change kbytes_written value

### ISSUE THREAD

**Issue by JsBergbau** [tytso/e2fsprogs#36]
Trying:
```
sudo debugfs
open -w /dev/mmcblk0p2
set_super_value kbytes_written 1024
```
Prints error 
```
64-bit field kbytes_written has a second 64-bit field
defined; BUG?!?
```
Version: `debugfs 1.46-WIP (20-Mar-2020)`

Can you please take a look whats wrong here?

**Comment by tytso** [comment]
Thanks for the bug report!  This is now fixed in the maint branch.
