### ISSUE TITLE
Error messages when mkfs.ext /dev/loop 

### ISSUE THREAD

**Issue by YanfeiXu** [tytso/e2fsprogs#39]
Hi expert,
During mkfs.ext /dev/loop which losetup with an image placed in tmpfs. I got the following ERROR messages:
[  183.110770] blk_update_request: I/O error, dev loop6, sector 524160 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0
[  183.123949] blk_update_request: I/O error, dev loop6, sector 522 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0
[  183.137123] blk_update_request: I/O error, dev loop6, sector 16906 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0
[  183.150314] blk_update_request: I/O error, dev loop6, sector 32774 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0
[  183.163551] blk_update_request: I/O error, dev loop6, sector 49674 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0
[  183.176824] blk_update_request: I/O error, dev loop6, sector 65542 op 0x9:(WRITE_ZEROES) flags 0x1000800 phys_seg 0 prio class 0 
....
Reasons for this issue is shmem_fallocate doesn't support FL_ZERO_RANGE and some modifies of processing REQ_OP_WRITE_ZEROES with REQ_NOUNMAP were introduced from commit:efcfec57[loop: fix no-unmap write-zeroes request behavior] in v5.2 kernel.
You can see https://lkml.org/lkml/2020/5/13/1213 for more informations.

**Comment by tytso** [comment]
That's just the kernel being overly verbose.  The only way we can figure out whether or not a device supports write-zeros is to try it.   If it fails, we will fall back to other options.   Not a e2fsprogs bug. this is working as intended.
