### ISSUE TITLE
fuse2fs on chromeos for GIT

### ISSUE THREAD

**Issue by eepgwde** [tytso/e2fsprogs#55]
I'm using fuse2fs on chromeos because no loop devices. 
I have a 16GB file on an SD card accessible via 9p. I've made a filesystem within the file with mkfs.ext2. 

My fuse.conf has user_allow_other. I'm running fuse2fs as my own user. 
The filesystem works for most things I've tried, but not for git clone.

Git clone fails with a Permission Denied.

Cloning into 'spacemacs.d'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (39/39), done.
fatal: Unable to create temporary file '/a/lydia/homes/lydia/disk01/weaves/spacemacs.d/.git/objects/pack/tmp_pack_XXXXXX': Permission denied
fatal: index-pack failed

I tried a few switches: default_permissions and allow other. 
I've tried mounting as root with allow_other. 

It's always annoying that Git needs to do so much work with the underlying filesystem. I had hoped by using fuse2fs I could use Git on distributions on a large SD card. It seems not, I hope you can do something.

**Comment by tytso** [comment]
Hmm, seems to work for me:

% mke2fs -q -t ext4 -O ^has_journal -E root_owner=$UID:$UID /tmp/foo.img 1G
% fuse2fs /tmp/foo.img ~/mnt
% git clone /usr/projects/e2fsprogs/base ~/mnt/e2fsprogs
Cloning into '/home/tytso/mnt/e2fsprogs'...
done.
% df ~/mnt
Filesystem     1K-blocks   Used Available Use% Mounted on
/tmp/foo.img     1032124 107132    872564  11% /home/tytso/mnt

I am using fuse2fs from e2fsprogs 1.44.5 and git version 2.28.0

This also worked for me by using fuse2fs -o fakeroot, in which case you can drop the "-E root_owner..." from mke2fs.    $UID resolve to the user id of the current user.  That's a bash'ism, so if you're not using bash as your shell, you may need to specify the numeric UID explicitly.   The second $UID is to specify the group id that should own the root directory; most Linux systems have a convention that  users are created with the same numeric group id  as their primary group as their user id.   But if your uid is 1234, and your primary group id is, say, 100, you would enter -E root_owner=1234:100. 

See the mke2fs man page and the fuse2fs man pages for more details.
