### ISSUE TITLE
qsort_r not defined in musl

### ISSUE THREAD

**Issue by cemkeylan** [tytso/e2fsprogs#58]
Hello,

The latest version of e2fsprogs uses `qsort_r` on `e2fsck/rehash.c`. However, `qsort_r` is a Glibc specific function and is not supported in Musl C library. Previous versions only used `qsort` for the same functionality.

**Comment by tytso** [comment]
Thanks for the bug report.  It sounds like we'll need to use something like this, probably included into e2fsprogs's lib/support library:

https://github.com/noporpoise/sort_r

**Comment by cemkeylan** [comment]
The problem is resolved in `1.46.1`. Should I close this issue?
