### ISSUE TITLE
ext2fs_rw_bitmaps uses an extra thread on uniprocessor systems

### ISSUE THREAD

**Issue by BinaryWarlock** [tytso/e2fsprogs#67]
https://github.com/tytso/e2fsprogs/blob/67f2b54667e65cf5a478fcea8b85722be9ee6e8d/lib/ext2fs/rw_bitmaps.c#L543-L549

There's a `num_threads == 1` check that short-circuits to not spawning additional threads, but it's *before* getting the number of CPUs. If `sysconf(_SC_NPROCESSORS_CONF) == 1` (a single CPU system) then it will still spawn an additional thread.

But isn't it intended to not spawn more threads if `num_threads == 1` as in the first check? Perhaps the check should come after checking the number of CPUs?

By the way, do you think it should avoid threading if `fuse2fs` is passed the `-s` (single-threaded) option? (Would this be as trivial as not including `EXT2_FLAG_THREADS` if `-s` is passed?)

**Comment by tytso** [comment]
Fixed in 1.46.3.
