### ISSUE TITLE
Generic *print version* parameter for all tools

### ISSUE THREAD

**Issue by aparcar** [tytso/e2fsprogs#73]
Hi, would it be possible to add a `-v` aka `--version` argument to all tools of e2fsprogs so it's possible to know what's currently installed?

**Comment by tytso** [comment]
Many of the tools use -V to print the current version.   (-v generally means "verbose").   For example:

% e2fsck -V
e2fsck 1.46.2 (28-Feb-2021)
        Using EXT2FS Library version 1.46.2, 28-Feb-2021

In some cases the -V option character conflicts with some other use prior use, so it's not possible to use -V for that command .   For portability reasons (e2fsprogs also builds on NetBSD, MacOS X, etc --- Linux isn't the only OS in the world, you know!) we don't use getopt_long(3), which is a glibc'ism.   As a result we don't support long options such as --version.

At least in the Linux world, most of the time, people will use the distribution's package to determine what package is installed, e.g., "rpm -q e2fsprogs" or "dpkg -l e2fsprogs".

**Comment by aparcar** [comment]
> Many of the tools use -V to print the current version. (-v generally means "verbose"). For example:

I forgot to try the upper case one, thanks.

> At least in the Linux world, most of the time, people will use the distribution's package to determine what package is installed, e.g., "rpm -q e2fsprogs" or "dpkg -l e2fsprogs".

Sure, however over at OpenWrt we compile it from source to be a bit more distro independent. Anyway -V should do the trick, thanks!
